export const Config = {
  formSettingVariable: {
    PostDlvPendingForm: 'post-dlv-pending-form',
    VoucherPendingForm: 'voucher-pending-form',
    attendance: 'attendance',
    organization: 'organization',
    users: 'users',
    areas: 'areas',
  },
  messages: {
    addedSuccessfully: 'Added Successfully',
    updatedSuccessfully: 'Updated Successfully',
    deletedSuccessfully: 'Deleted Successfully',
    savedSuccessfully: 'Details Saved Successfully',
    vehiclesPresent: 'Already Present Vehicles',
    errorOccurred: 'Error Occurred. Please try again',
    pleaseWait: 'Please wait...',
    openingCamera: 'Opening Camera',
    proccessImg: 'Processing Image...',
    refresh: 'Fetching Details from DB',
    logginIn: 'Logging you In...',
    noImportZSD: 'Shipments Already Added...',
    noImportZMM: 'Recievings Already Added...',
    logginOut: 'Logging you Out...',
    sentOTP: 'OTP sent on this Number. Please enter OTP',
    sendingOTP: 'Sending OTP...',
    uploadWait: 'Uploading Data',
    areYouSure: 'Are You Sure',
    emailExist: 'Email ID Already exist',
    contactExist: 'Contact Number already exist',
    smsError: 'OTP could not be sent. Please try Again Later!',
    invalidOTP: 'Invalid OTP',
    zsdSuccess: 'ZSD Uploaded Successfully',
    zmmSuccess: 'ZMM Uploaded Successfully',
    zsdInvalid: 'Invalid ZSD File',
    zmmInvalid: 'Invalid ZMM File',
    zsdNoData: 'No records to upload',
    zsdInvalidInvoiceNo: 'Invoice already added',
    add2Value: 'Please Add At Least 2 Value',
    fillAllExpenses: 'Please fill all the expenses',
    fillAllFields: 'Please fill all the fields',
    fillAllImages: 'Please add all the images',
    invalidAmount: 'Amount is not between defined limit ',
    markingAttendance: 'Marking your Attendance...',
    markAttendance: 'Attendance marked as Present',
    markAbsent: 'Attendance marked as Absent',
    locationNotFound: 'You are off Premises... Please go to your Workplace',
  },
  collection: {
    account: 'account',
    accountZMM: 'account-zmm',
    expenseType: 'expense-type',
    settings: 'settings',
    variables: 'variables',
    labourMaster: 'labour-master',
    vendorMaster: 'vendor-master',
    role: 'role',
    areas: 'areas',
    users: 'users',
    supplierMaster: 'supplier-master',
    transporterMaster: 'transporter-master',
    vehiclesCategory: 'vehicles-Category',
    vehicles: 'vehicles',
    shipments: 'shipments',
    recievings: 'recievings',
    zsd: 'zsd',
    zmm: 'zmm',
  },
  storage: {
    labourParty: 'labourParty-Library',
    vendors: 'vendors-Library',
    suppliers: 'suppliers-Library',
    userPhoto: 'user-photo',
    businessProfile: 'business-profile',
    vehicleDocuments: 'vehicle-Documnets',
    shipment: 'shipment',
  },
  permissions: {
    upload_new_zsd_file: 'upload_new_zsd_file',
    fill_shipment_voucher: 'fill_shipment_voucher',
    fill_post_delivery_form: 'fill_post_delivery_form',
    discard_vouchers: 'discard_vouchers',
    edit_account_settings: 'edit_account_settings',
    view_reports: 'view_reports',
  },
  localStorage: {
    userdata: 'userdata',
  },
  url: {
    dicebear: 'https://api.dicebear.com/7.x/initials/svg?seed=',
    defaultProfile:
      'https://ik.imagekit.io/xji6otwwkb/Profile.png?updatedAt=1680849745697',
  },
};
